export const RoomEvents = {
  join: 'room:join',
  leave: 'room:leave',
  quizStart: 'quiz:start',
  questionStart: 'question:start',
  answerSubmit: 'answer:submit',
  wordCloudSubmit: 'wordcloud:submit',
  wordCloudVote: 'wordcloud:vote',
  questionReveal: 'question:reveal',
  questionNext: 'question:next',
  quizComplete: 'quiz:complete',
  state: 'room:state',
  participantJoined: 'participant:joined',
  participantLeft: 'participant:left',
  quizStarted: 'quiz:started',
  questionStarted: 'question:started',
  questionRevealed: 'question:revealed',
  leaderboardUpdated: 'leaderboard:updated',
  wordCloudUpdated: 'wordcloud:updated',
  dashboardUpdated: 'dashboard:updated',
  quizCompleted: 'quiz:completed',
  error: 'room:error',
} as const;
